name: thanh-say-hello
on:
  push:
    branches: [main]

jobs:
  docker: #tên job
    runs-on: ubuntu-latest #config môi trường chạy
    steps: # các job nhỏ 
      - name: Checkout
        uses: actions/checkout@v2
