name: thanh-say-hello
on:
  push:
    branches: [main]

jobs:
  docker: #tên job
    runs-on: ubuntu-latest #config môi trường chạy
    steps: # các job nhỏ 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login docker
        uses: docker/login-action@v1
        with: # truyền thông tin vào config
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: setup Docker builx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cicd
      
      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}

